# Generated by Django 4.2.2 on 2024-06-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailsettings',
            options={'permissions': [('can_view_mail_settings', 'Может просматривать рассылки'), ('can_disable_mail_settings', 'Может отключать рассылки')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылки'},
        ),
    ]
