# Generated by Django 4.2.2 on 2024-06-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='mail_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailsettings', verbose_name='Настройка рассылки'),
        ),
    ]
