# Generated by Django 4.2.2 on 2024-06-27 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0004_alter_mailingattempt_mail_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailsettings',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время отправки рассылки'),
        ),
    ]
